/*
 * This source file was generated by the Gradle 'init' task
 */
package org.view;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import org.model.Produto;
import org.persistence.GenericDAO;
import org.persistence.PadariaDAO;

public class Main {
    public static void main(String[] args) {

        GenericDAO genericDAO = new GenericDAO();
		PadariaDAO pdDAO = new PadariaDAO(genericDAO);

        try {
			Connection connection = genericDAO.getConnection("padariaBD");
			String dbProdName = connection.getMetaData().getDatabaseProductName();
			String dbProdVersion = connection.getMetaData().getDatabaseProductVersion();
			System.out.println(dbProdName + " - " + dbProdVersion);
			
			List<Produto> produtos = pdDAO.getProdutos();
			produtos.forEach(prod -> System.out.println(prod.toString()));
		} catch (ClassNotFoundException | SQLException e) {
			System.err.println(e.getMessage());
			e.printStackTrace();
		}
		//A linha abaixo é para abrir a interface gráfica do menu principal
        //Application.launch(MenuPrincipal.class, args);
    }
}
